export interface Conference {
  name: string;
  broker: string;
  contact: string;
  eventType: string;
  startDate: string;
  finishDate: string;
  city: string;
  geography: string;
}

export const CONFERENCES: Conference[] = [
  { name: "Midcap Conference", broker: "Kotak Securities", contact: "", eventType: "Investor Conference", startDate: "26 Nov 2026", finishDate: "27 Nov 2026", city: "Mumbai", geography: "India" },
  { name: "Healthcare Forum", broker: "Kotak Securities", contact: "", eventType: "Investor Conference", startDate: "17 Sep 2026", finishDate: "18 Sep 2026", city: "Mumbai", geography: "India" },
  { name: "India Corporate Day", broker: "Kotak Securities", contact: "", eventType: "Investor Conference", startDate: "15 Jun 2026", finishDate: "17 Jun 2026", city: "London", geography: "United Kingdom" },
  { name: "India Corporate Day", broker: "Kotak Securities", contact: "", eventType: "Investor Conference", startDate: "08 Jun 2026", finishDate: "10 Jun 2026", city: "", geography: "Hong Kong" },
  { name: "Jefferies India Access Days", broker: "Jefferies", contact: "", eventType: "Investor Conference", startDate: "08 Jun 2026", finishDate: "09 Jun 2026", city: "New York", geography: "United States" },
  { name: "Citi India Conference", broker: "Citi Group", contact: "", eventType: "Investor Conference", startDate: "03 Jun 2026", finishDate: "05 Jun 2026", city: "Mumbai", geography: "India" },
  { name: "Axis Capital's Rising Stars Conference", broker: "Axis Capital", contact: "", eventType: "Investor Conference", startDate: "01 Jun 2026", finishDate: "02 Jun 2026", city: "Mumbai", geography: "India" },
  { name: "Bank of America Securities India Conference", broker: "", contact: "", eventType: "Investor Conference", startDate: "01 Jun 2026", finishDate: "04 Jun 2026", city: "Mumbai", geography: "India" },
  { name: "360 ONE Capital(B&K) 16th Annual Investor Conference-Trinity India 2026", broker: "360 ONE Capital(B&K)", contact: "Sanjeev Mohta", eventType: "Investor Conference", startDate: "27 May 2026", finishDate: "29 May 2026", city: "Mumbai", geography: "India" },
  { name: "Titans of Tomorrow Conference", broker: "Ambit Broking", contact: "", eventType: "Investor Conference", startDate: "25 May 2026", finishDate: "26 May 2026", city: "Mumbai", geography: "India" },
  { name: "B & K Trinity Conference", broker: "360 ONE Capital(B&K)", contact: "", eventType: "Investor Conference", startDate: "25 May 2026", finishDate: "29 May 2026", city: "Mumbai", geography: "India" },
  { name: "India Manthan: Rising Soft Power", broker: "YES Securities", contact: "", eventType: "Investor Conference", startDate: "21 May 2026", finishDate: "22 May 2026", city: "Mumbai", geography: "India" },
  { name: "Nakshatra III – Shining Stars Amid Global Turbulence", broker: "Centrum Broking", contact: "Shweta Raidas", eventType: "Investor Conference", startDate: "20 May 2026", finishDate: "22 May 2026", city: "Virtual", geography: "India" },
  { name: "Annual Singapore Corporate Day", broker: "Motilal Oswal", contact: "", eventType: "Investor Conference", startDate: "18 May 2026", finishDate: "19 May 2026", city: "", geography: "Singapore" },
  { name: "Yes Securities India Manthan Innaugural Flagship", broker: "YES Securities", contact: "", eventType: "Investor Conference", startDate: "05 May 2026", finishDate: "06 May 2026", city: "Mumbai", geography: "India" },
  { name: "DAM Capital Hospitals & Diagnostics conference", broker: "DAM Capital", contact: "Anifa Fernandes", eventType: "Investor Conference", startDate: "23 Mar 2026", finishDate: "23 Mar 2026", city: "Mumbai", geography: "India" },
  { name: "India Conclave Conference", broker: "Antique Securities", contact: "Bharati Ponda", eventType: "Investor Conference", startDate: "19 Mar 2026", finishDate: "19 Mar 2026", city: "", geography: "Singapore" },
  { name: "Jefferies LLC Asia Forum", broker: "Jefferies", contact: "", eventType: "Investor Conference", startDate: "17 Mar 2026", finishDate: "19 Mar 2026", city: "", geography: "Hong Kong" },
  { name: "Avendus Spark INDX", broker: "Avendus Spark", contact: "", eventType: "Investor Conference", startDate: "10 Mar 2026", finishDate: "11 Mar 2026", city: "London", geography: "United Kingdom" },
  { name: "Data Center Ecosystem", broker: "JM Financial", contact: "", eventType: "Investor Conference", startDate: "09 Mar 2026", finishDate: "09 Mar 2026", city: "Mumbai", geography: "India" },
  { name: "J.P. Morgan India Forum", broker: "JP Morgan (India)", contact: "", eventType: "Investor Conference", startDate: "09 Mar 2026", finishDate: "10 Mar 2026", city: "", geography: "Singapore" },
  { name: "Investec India Promoter and Founder Conference", broker: "Investec (India)", contact: "", eventType: "Investor Conference", startDate: "09 Mar 2026", finishDate: "12 Mar 2026", city: "Mumbai", geography: "India" },
  { name: "Bharat Connect Conference", broker: "Arihant Capital Market", contact: "Ashvath Rajan", eventType: "Investor Conference", startDate: "09 Mar 2026", finishDate: "11 Mar 2026", city: "Virtual", geography: "India" },
  { name: "IIFL Conference", broker: "", contact: "", eventType: "Investor Conference", startDate: "24 Feb 2026", finishDate: "26 Feb 2026", city: "Mumbai", geography: "India" },
  { name: "Chasing Growth Annual Conference", broker: "Kotak Securities", contact: "", eventType: "Investor Conference", startDate: "23 Feb 2026", finishDate: "27 Feb 2026", city: "Mumbai", geography: "India" },
  { name: "Decoding Growth Strategies", broker: "Dolat Capital", contact: "", eventType: "Investor Conference", startDate: "18 Feb 2026", finishDate: "18 Feb 2026", city: "Mumbai", geography: "India" },
  { name: "Axis Capital India Conference", broker: "Axis Capital", contact: "", eventType: "Investor Conference", startDate: "10 Feb 2026", finishDate: "12 Feb 2026", city: "Mumbai", geography: "India" },
  { name: "Nuvama India Conference", broker: "Nuvama Group", contact: "", eventType: "Investor Conference", startDate: "09 Feb 2026", finishDate: "11 Feb 2026", city: "Mumbai", geography: "India" },
  { name: "Systematix India Annual Conference", broker: "Systematix", contact: "Mrunal Pawar", eventType: "Investor Conference", startDate: "09 Feb 2026", finishDate: "10 Feb 2026", city: "Mumbai", geography: "India" },
  { name: "JMFL SGP Conference", broker: "", contact: "", eventType: "Investor Conference", startDate: "05 Feb 2026", finishDate: "06 Feb 2026", city: "Mumbai", geography: "India" },
  { name: "Asia Conference", broker: "Elara Capital", contact: "Anita Nazareth", eventType: "Investor Conference", startDate: "03 Dec 2025", finishDate: "05 Dec 2025", city: "", geography: "Singapore" },
  { name: "Asia Conference", broker: "Elara Capital", contact: "Anita Nazareth", eventType: "Investor Conference", startDate: "03 Dec 2025", finishDate: "05 Dec 2025", city: "", geography: "Hong Kong" },
  { name: "Midcap Conference 2025", broker: "Kotak Securities", contact: "Weibke Ann Coutinho", eventType: "Investor Conference", startDate: "20 Nov 2025", finishDate: "21 Nov 2025", city: "Mumbai", geography: "India" },
  { name: "US Conference", broker: "Elara Capital", contact: "Anita Nazareth", eventType: "Investor Conference", startDate: "17 Nov 2025", finishDate: "17 Nov 2025", city: "New York", geography: "United States" },
  { name: "Annual Investor Conference", broker: "Avendus Spark", contact: "Arundhati Kursange", eventType: "Investor Conference", startDate: "17 Nov 2025", finishDate: "19 Nov 2025", city: "Mumbai", geography: "India" },
  { name: "UK Conference", broker: "Elara Capital", contact: "Anita Nazareth", eventType: "Investor Conference", startDate: "13 Nov 2025", finishDate: "14 Nov 2025", city: "Edinburgh", geography: "United Kingdom" },
  { name: "UK Conference", broker: "Elara Capital", contact: "Anita Nazareth", eventType: "Investor Conference", startDate: "13 Nov 2025", finishDate: "14 Nov 2025", city: "London", geography: "United Kingdom" },
  { name: "G-200 Summit: Unstoppable Bharat", broker: "Anand Rathi", contact: "Vishal Laddha", eventType: "Investor Conference", startDate: "12 Nov 2025", finishDate: "14 Nov 2025", city: "Mumbai", geography: "India" },
  { name: "Financial Conference", broker: "JP Morgan (India)", contact: "", eventType: "Investor Conference", startDate: "22 Sep 2025", finishDate: "23 Sep 2025", city: "Mumbai", geography: "India" },
  { name: "Conference", broker: "JM Financial", contact: "", eventType: "Investor Conference", startDate: "17 Sep 2025", finishDate: "18 Sep 2025", city: "New York", geography: "United States" },
  { name: "India Forum", broker: "Jefferies", contact: "", eventType: "Investor Conference", startDate: "16 Sep 2025", finishDate: "18 Sep 2025", city: "Gurugram", geography: "India" },
  { name: "Conference", broker: "JM Financial", contact: "", eventType: "Investor Conference", startDate: "15 Sep 2025", finishDate: "16 Sep 2025", city: "London", geography: "United Kingdom" },
  { name: "Flagship Investor Forum", broker: "CLSA (India)", contact: "", eventType: "Investor Conference", startDate: "11 Sep 2025", finishDate: "12 Sep 2025", city: "", geography: "Hong Kong" },
  { name: "Conference", broker: "CLSA (India)", contact: "", eventType: "Investor Conference", startDate: "08 Sep 2025", finishDate: "11 Sep 2025", city: "", geography: "Hong Kong" },
  { name: "Asia Forum", broker: "Jefferies", contact: "", eventType: "Investor Conference", startDate: "08 Sep 2025", finishDate: "10 Sep 2025", city: "", geography: "Hong Kong" },
  { name: "Conference", broker: "Citi Group", contact: "", eventType: "Investor Conference", startDate: "03 Sep 2025", finishDate: "05 Sep 2025", city: "New York", geography: "United States" },
  { name: "Eleventh Edition of the Ashwamedh", broker: "Elara Capital", contact: "Tina D souza", eventType: "Investor Conference", startDate: "01 Sep 2025", finishDate: "04 Sep 2025", city: "Mumbai", geography: "India" },
  { name: "Home Improvement Conference", broker: "Nuvama Group", contact: "", eventType: "Investor Conference", startDate: "25 Aug 2025", finishDate: "25 Aug 2025", city: "Mumbai", geography: "India" },
  { name: "India Conference", broker: "Ambit Broking", contact: "", eventType: "Investor Conference", startDate: "21 Aug 2025", finishDate: "22 Aug 2025", city: "", geography: "Singapore" },
  { name: "Powering Through - India on the Global Stage", broker: "Centrum Broking", contact: "Shweta Raidas", eventType: "Investor Conference", startDate: "20 Aug 2025", finishDate: "22 Aug 2025", city: "Virtual", geography: "India" },
  { name: "Flagship Investor conference", broker: "Antique Securities", contact: "Dhirendra Tiwari", eventType: "Investor Conference", startDate: "20 Aug 2025", finishDate: "22 Aug 2025", city: "Mumbai", geography: "India" },
  { name: "Alcoholic Beverages Sector Conference", broker: "DAM Capital", contact: "Anifa Fernandes", eventType: "Investor Conference", startDate: "20 Aug 2025", finishDate: "20 Aug 2025", city: "Mumbai", geography: "India" },
  { name: "Annual India Conference", broker: "Equirus", contact: "", eventType: "Investor Conference", startDate: "19 Aug 2025", finishDate: "20 Aug 2025", city: "Mumbai", geography: "India" },
  { name: "Conference", broker: "JM Financial", contact: "", eventType: "Investor Conference", startDate: "18 Aug 2025", finishDate: "19 Aug 2025", city: "Mumbai", geography: "India" },
  { name: "Asia Edition 2025", broker: "Avendus Spark", contact: "", eventType: "Investor Conference", startDate: "13 Aug 2025", finishDate: "14 Aug 2025", city: "", geography: "Singapore" },
  { name: "Asia Edition 2025", broker: "Avendus Spark", contact: "", eventType: "Investor Conference", startDate: "12 Aug 2025", finishDate: "12 Aug 2025", city: "", geography: "Hong Kong" },
  { name: "Investor Conference", broker: "Nirmal Bang", contact: "", eventType: "Investor Conference", startDate: "11 Aug 2025", finishDate: "14 Aug 2025", city: "Mumbai", geography: "India" },
  { name: "Conference", broker: "Nuvama Group", contact: "", eventType: "Investor Conference", startDate: "08 Aug 2025", finishDate: "08 Aug 2025", city: "", geography: "Hong Kong" },
  { name: "Conference", broker: "Nuvama Group", contact: "", eventType: "Investor Conference", startDate: "06 Aug 2025", finishDate: "07 Aug 2025", city: "", geography: "Singapore" },
  { name: "Specialty Chemicals and Healthcare Investor Conference", broker: "Nuvama Group", contact: "Archit Joshi", eventType: "Investor Conference", startDate: "25 Jun 2025", finishDate: "25 Jun 2025", city: "Mumbai", geography: "India" },
  { name: "Invest India Conference", broker: "IIFL Capital", contact: "", eventType: "Investor Conference", startDate: "24 Jun 2025", finishDate: "25 Jun 2025", city: "London", geography: "United Kingdom" },
  { name: "India Corporate Day", broker: "Kotak Securities", contact: "", eventType: "Investor Conference", startDate: "23 Jun 2025", finishDate: "24 Jun 2025", city: "London", geography: "United Kingdom" },
  { name: "India Consumer Conference 3.0", broker: "Anand Rathi", contact: "Bhargavi Kini", eventType: "Investor Conference", startDate: "19 Jun 2025", finishDate: "20 Jun 2025", city: "Virtual", geography: "India" },
  { name: "Asia CXO Conference", broker: "Investec (India)", contact: "", eventType: "Investor Conference", startDate: "11 Jun 2025", finishDate: "12 Jun 2025", city: "", geography: "Singapore" },
  { name: "India Corporate Day", broker: "Kotak Securities", contact: "", eventType: "Investor Conference", startDate: "11 Jun 2025", finishDate: "11 Jun 2025", city: "", geography: "Hong Kong" },
  { name: "India NYC Access Day", broker: "Jefferies", contact: "", eventType: "Investor Conference", startDate: "09 Jun 2025", finishDate: "10 Jun 2025", city: "New York", geography: "United States" },
  { name: "India Corporate Day", broker: "Kotak Securities", contact: "", eventType: "Investor Conference", startDate: "09 Jun 2025", finishDate: "10 Jun 2025", city: "", geography: "Singapore" },
  { name: "15th Annual Investor Conference - TRINITY INDIA 2025", broker: "360 ONE Capital(B&K)", contact: "Sanjeev Mohta", eventType: "Investor Conference", startDate: "28 May 2025", finishDate: "30 May 2025", city: "Mumbai", geography: "India" },
  { name: "Investment Conference", broker: "UBS (India)", contact: "", eventType: "Investor Conference", startDate: "27 May 2025", finishDate: "29 May 2025", city: "", geography: "Hong Kong" },
  { name: "Investor Conference", broker: "Nirmal Bang", contact: "", eventType: "Investor Conference", startDate: "26 May 2025", finishDate: "27 May 2025", city: "Mumbai", geography: "India" },
  { name: "Ambit India Access | Titans of Tomorrow", broker: "Ambit Broking", contact: "Bijal Thakkar", eventType: "Investor Conference", startDate: "26 May 2025", finishDate: "27 May 2025", city: "Mumbai", geography: "India" },
  { name: "Annual Conference", broker: "Mirae Asset CM (Sharekhan)", contact: "Kripashankar Maurya", eventType: "Investor Conference", startDate: "22 May 2025", finishDate: "23 May 2025", city: "Mumbai", geography: "India" },
  { name: "Nakshatra Conference", broker: "Centrum Broking", contact: "", eventType: "Investor Conference", startDate: "20 May 2025", finishDate: "21 May 2025", city: "Mumbai", geography: "India" },
  { name: "Asia Conference", broker: "Macquarie (India)", contact: "", eventType: "Investor Conference", startDate: "14 May 2025", finishDate: "15 May 2025", city: "", geography: "Hong Kong" },
  { name: "Bharat Connect Conference: Rising Stars - March 2025", broker: "Arihant Capital Market", contact: "", eventType: "Investor Conference", startDate: "25 Mar 2025", finishDate: "27 Mar 2025", city: "Virtual", geography: "India" },
  { name: "11th India Ideation Conference", broker: "Motilal Oswal", contact: "", eventType: "Investor Conference", startDate: "24 Mar 2025", finishDate: "25 Mar 2025", city: "Mumbai", geography: "India" },
  { name: "Auto Ancillary Conference", broker: "DAM Capital", contact: "Anifa Fernandes", eventType: "Investor Conference", startDate: "18 Mar 2025", finishDate: "18 Mar 2025", city: "Mumbai", geography: "India" },
  { name: "Promoter & Founder Conference 2025", broker: "Investec (India)", contact: "Swapna Bhandarkar", eventType: "Investor Conference", startDate: "03 Mar 2025", finishDate: "05 Mar 2025", city: "Mumbai", geography: "India" },
  { name: "16th Enterprising India Global Investors' Conference", broker: "IIFL Securities", contact: "", eventType: "Investor Conference", startDate: "25 Feb 2025", finishDate: "27 Feb 2025", city: "Mumbai", geography: "India" },
  { name: "Kotak Chasing Growth 2025 Conference", broker: "Kotak Securities", contact: "", eventType: "Investor Conference", startDate: "17 Feb 2025", finishDate: "20 Feb 2025", city: "Mumbai", geography: "India" },
  { name: "India Capex – Rising like a Phoenix!", broker: "Antique Securities", contact: "Bharati Ponda", eventType: "Investor Conference", startDate: "13 Feb 2025", finishDate: "14 Feb 2025", city: "Mumbai", geography: "India" },
  { name: "Tech Renaissance 2025: Pioneering Breakthroughs in Fintech and Data Centre", broker: "Systematix", contact: "Mrunal Pawar", eventType: "Investor Conference", startDate: "13 Feb 2025", finishDate: "13 Feb 2025", city: "Mumbai", geography: "India" },
  { name: "20th India Conference", broker: "Nuvama Group", contact: "", eventType: "Investor Conference", startDate: "10 Feb 2025", finishDate: "12 Feb 2025", city: "Mumbai", geography: "India" },
  { name: "10th India Ideation Conference", broker: "Motilal Oswal", contact: "", eventType: "Investor Conference", startDate: "16 Dec 2024", finishDate: "17 Dec 2024", city: "Mumbai", geography: "India" },
  { name: "Emerging Midcap Stars", broker: "Emkay Global", contact: "", eventType: "Investor Conference", startDate: "11 Dec 2024", finishDate: "11 Dec 2024", city: "Mumbai", geography: "India" },
  { name: "Caravan", broker: "IIFL Securities", contact: "", eventType: "Investor Conference", startDate: "05 Dec 2024", finishDate: "06 Dec 2024", city: "Kolkata", geography: "India" },
  { name: "Alco Beverage Day", broker: "Systematix", contact: "Mrunal Pawar", eventType: "Investor Conference", startDate: "27 Nov 2024", finishDate: "27 Nov 2024", city: "Mumbai", geography: "India" },
  { name: "Midcap Conference 2024", broker: "Kotak Securities", contact: "", eventType: "Investor Conference", startDate: "21 Nov 2024", finishDate: "22 Nov 2024", city: "Mumbai", geography: "India" },
  { name: "India Conference 2024 - Reimagining the India Growth Story", broker: "JM Financial", contact: "", eventType: "Investor Conference", startDate: "19 Nov 2024", finishDate: "21 Nov 2024", city: "Mumbai", geography: "India" },
  { name: "G-200 Summit, The Rise of Bharat: Unlocking Potential, Unleashing Growth!", broker: "Anand Rathi", contact: "Vishal Laddha", eventType: "Investor Conference", startDate: "18 Nov 2024", finishDate: "20 Nov 2024", city: "Mumbai", geography: "India" },
  { name: "Annual Conference", broker: "Avendus Spark", contact: "Arundhati Kursange", eventType: "Investor Conference", startDate: "12 Nov 2024", finishDate: "14 Nov 2024", city: "Mumbai", geography: "India" },
];

export const BROKERS = Array.from(new Set(CONFERENCES.map(c => c.broker).filter(Boolean))).sort();
export const CITIES = Array.from(new Set(CONFERENCES.map(c => c.city).filter(Boolean))).sort();
export const GEOGRAPHIES = Array.from(new Set(CONFERENCES.map(c => c.geography).filter(Boolean))).sort();
