export interface Investor {
  name: string;
  address: string;
  city: string;
  country: string;
  comments: string;
}

export const INVESTORS: Investor[] = [
  { name: "Individual Investors | HNI", address: "Not Available", city: "Mumbai", country: "India", comments: "No public information available" },
  { name: "Envision Capital", address: "33 Maker Chambers VI, Jamnalal Bajaj Marg", city: "Mumbai", country: "India", comments: "An India-focused alternative asset manager specializing in public equity investments, with a strong emphasis on small- and mid-cap opportunities." },
  { name: "Abakkus AM", address: "Abakkus Corporate Center, 6th Floor, Param House, Shanti Nagar, Off Santacruz Chembur Link Road", city: "Mumbai", country: "India", comments: "Abakkus Asset Manager, manages USD 4.37 Billion, focusing on alpha generation in Indian equities via AIFs & PMS." },
  { name: "Nippon India MF", address: "4th Floor, Tower A, Peninsula Business Park, Lower Parel (W)", city: "Mumbai", country: "India", comments: "Nippon India Mutual Fund employs dynamic asset allocation, sector-specific equity focus. AUM is USD 72.4 billion" },
  { name: "White Oak MF", address: "Unit No B4, 6th Floor, Cnergy, Appasaheb Marathe Marg", city: "Mumbai", country: "India", comments: "Bottom-up stock selection, investing in scalable, well-managed firms. AUM was USD 8.0 billion" },
  { name: "Svan Investment Managers", address: "B wing, 1001, 10th floor, Kanakia wall street, Andheri kurla road, Chakala", city: "Mumbai", country: "India", comments: "Research-focused, data-driven investment management firm applying fundamental research and disciplined portfolio construction." },
  { name: "Sequent Investments", address: "B - 1505/06, Naman Midtown, Senapati Bapat Marg, Prabhadevi (W)", city: "Mumbai", country: "India", comments: "" },
  { name: "HDFC MF", address: "2nd Floor, H.T. Parekh Marg, 165-166, Backbay Reclamation, Churchgate", city: "Mumbai", country: "India", comments: "Identifies profitable opportunities, thorough research, managing risks. AUM was approximately $53.5 billion." },
  { name: "Lucky Investment", address: "702-B, Poonam Chambers, A Wing Dr Annie Beasant Road", city: "Mumbai", country: "India", comments: "" },
  { name: "Alchemy Capital Management", address: "B-4, Amerchand Mansion, 16, Madame Cama Road", city: "Mumbai", country: "India", comments: "Managing USD 1.4 Billion, specializes in growth-focused PMS and AIFs." },
  { name: "Roha AMC", address: "Lodha Supremus 2, Unit No. 314, B Wing, Wagle Industrial Estate", city: "Mumbai", country: "India", comments: "" },
  { name: "Robo Capital", address: "Building 4, North Wing, NESCO IT Park, Western Express Highway", city: "Mumbai", country: "India", comments: "Boutique financial services firm providing comprehensive investment solutions across multiple asset classes." },
  { name: "Motilal Oswal MF", address: "Motilal Oswal Tower, Gokhale Sayani road, Prabhadevi", city: "Mumbai", country: "India", comments: "QGLP approach — quality companies with strong growth potential. AUM is USD 12 billion" },
  { name: "Renaissance Investment Managers", address: "Office No. 718, 7th Floor, C Wing, Mittal Premises Commercials CHS", city: "Mumbai", country: "India", comments: "" },
  { name: "AUM Advisors", address: "1401 Arcadia, NCPA Marg", city: "Mumbai", country: "India", comments: "Focused on delivering superior absolute returns by applying a disciplined private-equity-style approach to public markets." },
  { name: "Quest Investment Advisors", address: "188/3, Gurukrupa Building, First Floor, Jain Society", city: "Mumbai", country: "India", comments: "Specialist equity-focused investment manager with over three decades of experience in active portfolio management." },
  { name: "ICICI Prudential AM", address: "ICICI Mutual Fund Tower, Vakola", city: "Mumbai", country: "India", comments: "Customer-centric investment strategy, focusing on long-term wealth creation. AUM was USD 103.4 Billion" },
  { name: "Mirae Asset MF", address: "Unit No. 606, 6th Floor, Windsor Building, Off C.S.T. Road, Kalina", city: "Mumbai", country: "India", comments: "Diversified mutual funds for wealth creation. AUM is USD 9.2 billion" },
  { name: "Sundaram MF", address: "No.46, 2nd Floor, Whites Road, Royapettah", city: "Chennai", country: "India", comments: "Active management, balancing equity and debt investments. AUM was USD 4.6 billion" },
  { name: "Electrum Capital", address: "1301, Morya Grand", city: "Mumbai", country: "India", comments: "Venture capital and growth equity platform investing across energy transition and sustainability ecosystem." },
  { name: "Niveshaay", address: "508 SNS Platina Vesu", city: "Surat", country: "India", comments: "Specializes in smallcase portfolios and manages AIFs. Focus on long-term growth themes." },
  { name: "Sapphire Capital", address: "Office No 6, 1st Floor, Delstar Building, Kemps Corner", city: "Mumbai", country: "India", comments: "Real estate investment company with expertise in urban property investment opportunities." },
  { name: "Param Capital", address: "The Capital, Bandra Kurla Complex", city: "Mumbai", country: "India", comments: "High-growth investments in undervalued mid-cap and small-cap stocks. AUM is USD 250 million" },
  { name: "Ask Investment Managers", address: "Birla Aurora, 16 Level, Office Floor 9", city: "Mumbai", country: "India", comments: "Discretionary investment manager with long heritage in research-driven equity portfolio management." },
  { name: "Equitree Capital", address: "301, Tree Building 28, Senapati Bapat Road, Raghuvanshi Mills", city: "Mumbai", country: "India", comments: "Long-term deep-value investing in small and micro-cap Indian equities via concentrated portfolios." },
  { name: "Kotak Mahindra Asset Management", address: "7th Floor, 12 BKC, Plot No. C-12, G Block", city: "Mumbai", country: "India", comments: "Diverse range of mutual fund schemes. AUM was USD 58 Billion" },
  { name: "JM Financial MF", address: "7th Floor, Cnergy, Appasaheb Marathe Marg, Prabhadevi", city: "Mumbai", country: "India", comments: "Investment banking, wealth management, and asset management. AUM was USD 1.38 Billion" },
  { name: "Enam Asset Management", address: "810, Raheja Chambers, Free Press Journal Road", city: "Mumbai", country: "India", comments: "Long-term, ethical investments, prioritizing capital preservation. AUM was over $4 billion." },
  { name: "Arjav Partners", address: "415 Dalamal Towers, 211 Free Press Journal Marg, Nariman Point", city: "Mumbai", country: "India", comments: "Multi-investor office focusing on absolute returns through concentrated equity investing with 3-5 year horizon." },
  { name: "Birla Sun Life AMC", address: "No 841, 18th Flr, Elphinstone Road, One World Centre", city: "Mumbai", country: "India", comments: "Active management, diversification, and thematic investing. AUM of USD 45 Billion" },
  { name: "SKS Capital & Research", address: "1101 Lodha Supremes, 11th Floor, Senapati Bapat Marg, Lower Parel", city: "Mumbai", country: "India", comments: "Boutique investment management firm managing proprietary assets via alternative strategies." },
  { name: "OHM Portfolio Equi Research", address: "504/504A, 5th Floor, Ceejay House, Shivsagar Estate", city: "Mumbai", country: "India", comments: "Mumbai-based financial services firm providing institutional equity broking and research-driven portfolio management." },
  { name: "Nine Rivers Capital", address: "509-510, Meadows, Sahar Plaza, Andheri Kurla Road", city: "Mumbai", country: "India", comments: "Independent asset management focused on high-growth opportunities across small and mid-cap public equities." },
  { name: "Equentis Wealth", address: "A-603 Marathon Futurex, N.M. Joshi Marg, Lower Parel", city: "Mumbai", country: "India", comments: "Investment advisory and portfolio management firm. AUM ~USD 12 million." },
  { name: "Emkay Investment", address: "Paragon Centre, C 26-28, Second Floor, Pandhurang Budhkar Marg", city: "Mumbai", country: "India", comments: "Mumbai-based asset management firm offering active equity investment solutions." },
  { name: "UTI MF", address: "UTI Tower, Gn Block, Bandra Kurla Complex", city: "Mumbai", country: "India", comments: "Focuses on delivering long-term growth across equity and debt. AUM was USD 36 billion" },
  { name: "Karma Capital Advisors", address: "Floor 12U, Suite 1, Remi Commercio, Off Veera Desai Road", city: "Mumbai", country: "India", comments: "Focuses on India's growth story by investing in listed equities. AUM is USD 1.5 billion" },
  { name: "Aionios Alpha Investment Management", address: "418, Maker Chambers V, 221 Jamnalal Bajaj Marg, Nariman Point", city: "Mumbai", country: "India", comments: "Concentrated, benchmark-agnostic portfolio of 20-25 stocks with 3+ year horizon." },
  { name: "NV Alpha FM", address: "101, 1st floor, D-Block, Shiv Sagar Estate", city: "Mumbai", country: "India", comments: "Boutique investment management firm with private-equity mindset." },
  { name: "Moneybee Securities", address: "303, Tower - A, Peninsula Business Park, G. K. Marg", city: "Mumbai", country: "India", comments: "Equity investments using research-driven approach, sectoral diversification." },
  { name: "Fractal Capital Investments", address: "17th Floor, Innov8, A-Wing, Parinee Crescenzo, C-30, G-Block", city: "Mumbai", country: "India", comments: "Specialist investment management seeking to identify recurring patterns and intrinsic value." },
  { name: "Nuvama AM", address: "801-804, Wing A, Building No. 3, Inspire BKC, G Block", city: "Mumbai", country: "India", comments: "Bespoke investment strategies for HNIs and UHNIs. AUM is 921 million" },
  { name: "Monarch Networth Capital", address: "G Block B Wing 4th Floor, Laxmi Towers, Bandra Kurla Complex", city: "Mumbai", country: "India", comments: "Financial services like stockbroking, wealth management, and mutual fund distribution." },
  { name: "DSP MF", address: "Mafatlal Centre 10th Floor, Nariman Point", city: "Mumbai", country: "India", comments: "Family-owned investment manager offering wide spectrum of mutual fund products." },
  { name: "Axis AM", address: "23rd Floor, One Lodha Place, S. B. Road", city: "Mumbai", country: "India", comments: "Disciplined, long-term investing through SIPs. AUM was USD 38 Billion" },
  { name: "Girik Wealth Advisors", address: "1018, Makers Chamber V", city: "Mumbai", country: "India", comments: "Focuses on high-growth, quality businesses. AUM was $185.7 million" },
  { name: "SageOne IM", address: "10, 4th Floor, Suyog Platinum Tower, Koregaon Park", city: "Pune", country: "India", comments: "Invests in high-growth Indian businesses with ethical management. AUM was $675 million." },
  { name: "Banyan Capital Advisors", address: "D- 51, Ground Floor, Gulmohar Park", city: "New Delhi", country: "India", comments: "" },
  { name: "JM Financial Services", address: "7th Floor, Cnergy, Appasaheb Marathe Marg, Prabhadevi", city: "Mumbai", country: "India", comments: "Investment banking, mortgage lending, alternative credit, asset management. AUM was USD 1.38 Billion" },
  { name: "Motilal Oswal AM", address: "10th Floor, Motilal Oswal Tower, Rahimtullah Sayani Road", city: "Mumbai", country: "India", comments: "High-growth equities, emphasizing small- and mid-cap stocks. AUM is USD 13.3 billion" },
  { name: "GeeCee Investments", address: "209-210, Arcadia Building, 2nd Floor, NCPA Marg, Nariman Point", city: "Mumbai", country: "India", comments: "Real estate development, financial investments, and renewable energy." },
  { name: "Mittal Analytics", address: "4F - 403, Shalimar Iridium, Vibhuti Khand, Gomtinagar", city: "Lucknow", country: "India", comments: "SEBI-registered portfolio manager focused on long-term fundamental investing." },
  { name: "Subhkam Ventures (FO)", address: "Maker Chamber IV, 14th Floor, 222, Nariman Point", city: "Mumbai", country: "India", comments: "Diversified and research-intensive investment strategy across public and private markets." },
  { name: "Tata MF", address: "1903, B Wing, Parinee Crescenzo, G Block BKC", city: "Mumbai", country: "India", comments: "Leading Indian mutual fund house since 1994. Research-based, long-term investment strategy." },
  { name: "Old Bridge MF", address: "1705, C Wing, One BKC, G Block BKC", city: "Mumbai", country: "India", comments: "Long-term investments in low-risk, market-leading companies. AUM is USD 800 million" },
  { name: "Ambit Investment Advisors", address: "Ambit House, 449, Senapati Bapat Marg", city: "Mumbai", country: "India", comments: "India-focused diversified financial services platform serving institutional investors." },
  { name: "Bandhan AMC", address: "6th Floor, Tower 1C, One World Center, Senapati Bapat Marg", city: "Mumbai", country: "India", comments: "Focused on delivering superior investment solutions across diverse asset classes." },
  { name: "Invesco AM (IN)", address: "2101-A, A Wing, 21st Floor, Marathon Futurex, N. M. Joshi Marg", city: "Mumbai", country: "India", comments: "Macroeconomic analysis, credit assessment, portfolio construction. AUM was USD 1.8 Trillion" },
  { name: "Unifi Capital", address: "3201,02, A-wing, Marathon Futurex, NM Joshi Marg, Lower Parel", city: "Mumbai", country: "India", comments: "India-focused asset management with thematic and research-driven investment approach." },
  { name: "Omkara Capital", address: "Unit no. 207 A/B, Peninsula Centre, Parel East", city: "Mumbai", country: "India", comments: "Mumbai-based equity research and advisory focused on mid- and small-cap Indian companies." },
  { name: "Union MF", address: "Unit 503, 5th Floor, Leela Business Park, Andheri East", city: "Mumbai", country: "India", comments: "Various mutual fund schemes across equity, debt, and hybrid. AUM as of Dec'24: USD 650 million" },
  { name: "Aequitas Investment", address: "A-1003, The Capital Building, BKC", city: "Mumbai", country: "India", comments: "Founded in 2013. AUM reaching INR 8700 Cr by 2026." },
  { name: "Goldman Sachs AM (India)", address: "Rational House, 951-A, Appasaheb Marathe Marg", city: "Mumbai", country: "India", comments: "Capitalizing on economic growth, selective investments. AUM was $3.1 trillion" },
  { name: "Bay Capital IA", address: "14th Floor Bakhtawar", city: "Mumbai", country: "India", comments: "Long-term equity investments in high-growth companies. AUM is USD 700 million" },
  { name: "Invexa Capital", address: "11th floor, Express Towers, Nariman Point", city: "Mumbai", country: "India", comments: "Concentrated, medium-term India investment strategy, blending macro insights with bottom-up research." },
  { name: "Stallion Asset", address: "1001, Omkar The Summit Business Bay, Andheri Kurla Road", city: "Mumbai", country: "India", comments: "SEBI-registered PMS firm offering growth-oriented equity investment solutions." },
  { name: "Franklin Templeton AM (IN)", address: "One International Centre, Tower 2, 12th Floor, Senapati Bapat Marg", city: "Mumbai", country: "India", comments: "India-focused asset management offering broad suite of mutual fund solutions." },
  { name: "Canara Robeco AM", address: "4th Floor, Construction House, 5, Walchand Hirachand Marg, Ballard Estate", city: "Mumbai", country: "India", comments: "Long-term capital appreciation with balanced approach to equity and debt. AUM USD 8.03 billion" },
  { name: "Max Life Insurance", address: "2nd Floor, Baba House, Sir Mathuradas Vasanji Rd, Andheri East", city: "Mumbai", country: "India", comments: "Long-term wealth creation through ULIPs and mutual funds. AUM is USD 18 billion" },
  { name: "Mahindra Manulife MF", address: "Unit No. 204, 2nd Floor, Amiti Building, Piramal Agastya Corporate Park", city: "Mumbai", country: "India", comments: "Diversified equity, fixed income, and ESG investments." },
  { name: "LIC MF", address: "Industrial Assurance Building, 4th Floor, Opp. Churchgate Station", city: "Mumbai", country: "India", comments: "Wide range of equity, debt, hybrid, and index funds. AUM is USD 6.85 billion" },
  { name: "Sameeksha Capital", address: "1202, South Tower, One42, Chhanalal Joshi Marg", city: "Ahmedabad", country: "India", comments: "SEBI-registered portfolio manager focused on long-only investments in Indian listed equities." },
  { name: "Entrust Family Office", address: "710, 7th Floor, Madhava Bldg., C-5 E Block", city: "Mumbai", country: "India", comments: "Boutique multi-family office offering personalized investment advisory and portfolio management." },
  { name: "Kotak Mahindra MF", address: "2nd Floor, 12-BKC, Plot No C-12, G Block", city: "Mumbai", country: "India", comments: "Managing alternative assets like real estate, credit. AUM is USD 45.5 billion" },
  { name: "360 One AM", address: "Senapati Bapat Marg, Kamla City", city: "Mumbai", country: "India", comments: "India-focused integrated wealth and asset management platform." },
  { name: "PGIM AM (IN)", address: "Laxmi Tower, 4th Floor, G Block, BKC", city: "Mumbai", country: "India", comments: "Equity, debt, hybrid, and international funds. AUM was about $3.19 billion." },
  { name: "Marcellus Investment Managers", address: "102, First Floor, Boston House, Suren Road", city: "Mumbai", country: "India", comments: "Specialist investment manager focused on long-term wealth creation with forensic accounting framework." },
  { name: "Malabar Investments", address: "The Point, 2nd Floor, 30th Road, Bandra West", city: "Mumbai", country: "India", comments: "Value-driven strategy focusing on IT and media sectors. AUM is USD 1 billion" },
  { name: "PineBridge (IN)", address: "Unit No.1101, Tower B, Peninsula Business Park", city: "Mumbai", country: "India", comments: "Active, high-conviction investing. AUM was USD 152.9 billion" },
  { name: "Ashmore (India)", address: "207 Ceejay House, Shivsagar Estate, Worli", city: "Mumbai", country: "India", comments: "Specializes in Emerging Markets investments. AUM was USD 51.8 Billion" },
  { name: "Piper Serica Advisors", address: "Office No. 905 & 906, A Wing, 9th Floor, Marathon Innova Nextgen", city: "Mumbai", country: "India", comments: "Focuses on high-growth sectors and market leaders. AUM was $103 million." },
  { name: "Quantum Advisors", address: "1st Floor, Apeejay House, 3 Dinshaw Vachha Road, Nariman Point", city: "Mumbai", country: "India", comments: "Ethical, ESG-driven investing, multi-asset strategies. AUM was approx $29.8 billion" },
  { name: "Sanctum Wealth", address: "1401, Tower 2, 14th floor, One International Center, Senapati Bapat Marg", city: "Mumbai", country: "India", comments: "Dynamic investment strategy, adjusting asset allocations. AUM was more than USD 4 billion" },
  { name: "Catamaran Management (FO)", address: "51/52, 1st Main Rd, J. P. Nagar", city: "Bengaluru", country: "India", comments: "Identifies disruptive business ideas and investing in high-potential startups. AUM is USD 1 billion" },
  { name: "AM Investment", address: "73 Sarajevska, Suite 22", city: "Belgrade", country: "Serbia", comments: "" },
  { name: "Crown Capital Partners", address: "333 Bay St, Toronto, ON M5H 2R2", city: "Toronto", country: "Canada", comments: "" },
  { name: "Bamboo Capital Partners", address: "5, Place de la Gare, L-1616 Luxembourg", city: "Luxembourg", country: "Luxembourg", comments: "" },
  { name: "Bowhead Investment", address: "1271 Avenue of the Americas Ste 4300", city: "New York", country: "United States", comments: "" },
  { name: "Lotus Asset Management", address: "1020 13th Ave S", city: "Nashville", country: "United States", comments: "Alternative asset management focused on long-term risk-adjusted returns." },
  { name: "Nomura Investment", address: "", city: "Tokyo", country: "Japan", comments: "Dynamic asset allocation, leveraging global presence. AUM was USD 619 Billion" },
  { name: "Dymon Asia", address: "1 Temasek Avenue", city: "Singapore", country: "Singapore", comments: "Singapore-based alternative investment manager. AUM was USD 5.7 Billion" },
  { name: "Franklin Templeton (UAE)", address: "Level 2, East Wing, Gate Building, DIFC", city: "Dubai", country: "United Arab Emirates", comments: "" },
  { name: "Al Mal Capital", address: "Office 901, 48 Burj Gate, Downtown Dubai", city: "Dubai", country: "United Arab Emirates", comments: "" },
  { name: "Ajeej Capital", address: "Suite 203, Building 6, Gate Village, DIFC", city: "Dubai", country: "United Arab Emirates", comments: "" },
  { name: "Public Investment Fund", address: "Ministry of Finance, King Abdulaziz Road, 6th Floor", city: "Riyadh", country: "Saudi Arabia", comments: "" },
  { name: "NBK Capital", address: "NBK Tower, Sharq Area, Floor 34", city: "Kuwait City", country: "Kuwait", comments: "" },
  { name: "SICO", address: "BMB Building, 1st floor, Diplomatic Area", city: "Manama", country: "Bahrain", comments: "" },
  { name: "Bank Muscat", address: "311 Airport Heights Seeb 112", city: "Muscat", country: "Oman", comments: "" },
  { name: "Seven Canyons Advisors", address: "79 Main Street", city: "Salt Lake City", country: "United States", comments: "" },
  { name: "Minerva Advisors", address: "7 Adam Street The Strand London WC2N 6AA", city: "London", country: "United Kingdom", comments: "Specialist consultancy aiding government and commercial organizations." },
  { name: "Capital Group (India)", address: "3rd Floor, Unit 2, Vibgyor Tower Block G, BKC", city: "Mumbai", country: "India", comments: "Leading global investment management with fundamental, research-driven strategy." },
  { name: "SBI LI AM", address: "Natraj, M.V. Road, Western Express Highway Junction, Andheri East", city: "Mumbai", country: "India", comments: "Diversified portfolios to manage risk. AUM was USD 42.68 billion" },
  { name: "Buoyant Capital", address: "3501 Kohinoor Square N C Kelkar Marg", city: "Mumbai", country: "India", comments: "Flexi-cap investment strategy focusing on risk-adjusted returns across sectors." },
  { name: "Spark PWM", address: "Unit No. 1252, 5th Floor, Building No. 12, Solitaire Corporate Park", city: "Mumbai", country: "India", comments: "Tailored wealth solutions. AUM was USD 3.3 billion" },
  { name: "Varanium Capital Advisors", address: "1416, One Lodha Place, Senapati Bapat Marg", city: "Mumbai", country: "India", comments: "Customized investment solutions including equity, debt, and private equity." },
  { name: "Narotam Sekhsaria Family Office", address: "122, Maker Chambers III, 12th Floor, Nariman Point", city: "Mumbai", country: "India", comments: "Long-term, value-driven investments across technology, financial services, and retail." },
  { name: "Reliance General Insurance", address: "6th Floor, Oberoi Commerz, International Business Park", city: "Mumbai", country: "India", comments: "Diversified asset allocation with high-quality bonds. AUM was $2.03 billion" },
  { name: "Samena Capital Investments", address: "Office No. 815, C Wing, One BKC, G Block", city: "Mumbai", country: "India", comments: "" },
  { name: "Emerge Capital", address: "1705, 17th Floor, Max Towers", city: "New Delhi", country: "India", comments: "SEBI-registered Category III AIF focused on public markets and late-stage private market investments." },
  { name: "Neomile Capital", address: "C 1215, One BKC, Bandra Kurla Complex", city: "Mumbai", country: "India", comments: "Growth-stage investment firm providing equity funding from USD 2M to USD 75M." },
  { name: "Right Horizons Portfolio Management", address: "No 6, Ground Floor, Arakere, Bannerghatta Road", city: "Bangalore", country: "India", comments: "SEBI-registered portfolio management firm founded in 2012, managing over Rs. 1,400 crore in AUM." },
  { name: "Paladin Capital", address: "Atlanta, 146", city: "Mumbai", country: "India", comments: "Global multi-stage investor focused on cybersecurity. Managed over $2B in assets." },
  { name: "Ananta Capital", address: "3rd Floor, Brady House, 12/14, Veer Nariman Road, Fort", city: "Mumbai", country: "India", comments: "Long-term, patient capital emphasizing compounding value." },
  { name: "Barclays Securities (India)", address: "33rd Floor, Building Altimus, Worli Estate", city: "Mumbai", country: "India", comments: "" },
  { name: "Neo Asset Management", address: "903 - B Wing, Marathon Futurex, NM Joshi Marg", city: "Mumbai", country: "India", comments: "Mumbai-based alternative asset management firm focused on private market investment solutions." },
  { name: "Thinqwise Wealth Managers", address: "203-A, 2nd Floor, Center Point Building, Dr Baba Saheb Ambedkar Road", city: "Mumbai", country: "India", comments: "Boutique investment management firm focused on compounding capital over long periods." },
  { name: "Clockvine Capital Advisors", address: "306 B 3rd Floor, Lodha Supremus, Wadala (East)", city: "Mumbai", country: "India", comments: "SEBI-registered PMS firm. AUM approximately USD 16 million." },
  { name: "DR Choksey Finserv", address: "5th Floor, Abhishek Building, Andheri (West)", city: "Mumbai", country: "India", comments: "Manages approximately USD 77.48 million. Research-driven, conviction-based investing." },
  { name: "Ashika Group", address: "Altimus, Level 35, Dr. G. M. Bhosale Marg", city: "Mumbai", country: "India", comments: "Sector-agnostic, market-cap-agnostic investment strategy." },
  { name: "Bharti AXA LI", address: "Unit No. 1904, 19th Floor, Parinee Crescenzo, BKC", city: "Mumbai", country: "India", comments: "Life coverage, ULIPs, and savings plans. AUM approximately USD 1.91 Billion" },
  { name: "Prudent Investment Managers", address: "1st floor, Parinee Crescenzo", city: "Mumbai", country: "India", comments: "Tailored PMS, AIFs, and bespoke advisory for disciplined long-term wealth creation." },
  { name: "Aviva Life (India)", address: "401-A, The Kanakia wall street, Andheri East", city: "Mumbai", country: "India", comments: "JV between Dabur Invest Corp and Aviva. AUM USD 1.73 Billion" },
  { name: "VT Capital", address: "27AB Royd Street", city: "Kolkata", country: "India", comments: "Top-down thematic investment approach with research across 250+ companies." },
  { name: "Patni Advisors (FO)", address: "Shop No 72, Topiwala Centre, Goregaon West", city: "Mumbai", country: "India", comments: "Patni family office. Invests across stages in tech, healthcare, and consumer sectors." },
  { name: "Duro Capital", address: "Wework C20, G block, Bandra Kurla Complex", city: "Mumbai", country: "India", comments: "India-focused investment management firm investing in fairly priced businesses." },
  { name: "Singular Capital India Advisors", address: "C-1407, One BKC", city: "Mumbai", country: "India", comments: "Boutique investment manager focused on long-term capital appreciation." },
  { name: "Alfaccurate Advisors", address: "503, B Wing Naman Midtown, Off Senapati Bapat Marg", city: "Mumbai", country: "India", comments: "High-conviction, quality equity and alternative strategies." },
  { name: "Perpetuity", address: "Office 1-B, Unit no 214, A wing, The Capital, G Block, BKC", city: "Mumbai", country: "India", comments: "SEBI-registered Cat III AIF managing equity-focused funds with healthcare bias." },
  { name: "Steinberg AM (India)", address: "134, 13th Floor, Free Press House, 215 Nariman Point", city: "Mumbai", country: "India", comments: "Privately held investment adviser focused on value-oriented equity management." },
  { name: "ITI MF", address: "Naman Midtown, 21st Floor, A Wing, Prabhadevi", city: "Mumbai", country: "India", comments: "High-quality investment solutions for long-term wealth creation. AUM was USD 1.1 Billion" },
  { name: "Ardeko Investment", address: "501, 5th Floor, Naindhara Complex, Bodakdev", city: "Ahmedabad", country: "India", comments: "SEBI-registered PMS and RIA providing portfolio management and wealth management." },
  { name: "Bank of India IM", address: "B, 204, Tower 1, Peninsula Corporate Park", city: "Mumbai", country: "India", comments: "Active management with equity, debt, and hybrid funds. AUM approximately USD 1.39 billion" },
  { name: "M3 Investment", address: "810, Wing A, The Capital, Bandra Kurla Complex", city: "Mumbai", country: "India", comments: "Bilakhia Group family office focusing on Indian companies with growth potential." },
  { name: "L&T Asset Management", address: "6th floor, Mafatlal Centre, Nariman Point", city: "Mumbai", country: "India", comments: "" },
  { name: "Ampersand Capital", address: "72-A Mittal Tower, 210 Nariman Point", city: "Mumbai", country: "India", comments: "Private equity firm specializing in healthcare and industrial sectors." },
  { name: "IndiaFirst Life Insurance", address: "NESCO Center, 12th and 13th Floor, Tower 4, Goregaon", city: "Mumbai", country: "India", comments: "" },
  { name: "Capgrow Capital Advisors", address: "1519, 15th Floor, Lodha Codename No.1, Senapati Bapat Marg", city: "Mumbai", country: "India", comments: "" },
  { name: "Taurus MF", address: "3rd Floor, 301-304, Chandravillas, AML Centre 2", city: "Mumbai", country: "India", comments: "India-based asset management offering mutual fund products across equity, debt, hybrid strategies." },
  { name: "UBS (India)", address: "2/F, 2 North Avenue, Maker Max, BKC", city: "Mumbai", country: "India", comments: "" },
  { name: "DAM Capital", address: "G Block BKC, Bandra Kurla Complex", city: "Mumbai", country: "India", comments: "" },
  { name: "Axis Capital", address: "Axis House Wadia International Centre, Worli", city: "Mumbai", country: "India", comments: "Comprehensive financial solutions including investment banking and institutional equities." },
  { name: "PL Capital", address: "750 Eleventh Street South Suite 202", city: "Naples", country: "United States", comments: "India-based financial services platform since 1944." },
  { name: "Geojit Financial Services", address: "34/659-P, Civil Line Road Padivattom", city: "Kochi", country: "India", comments: "" },
  { name: "Multi Act-Equity Consultancy", address: "10th Floor, The Ruby, Tulsi Pipe Road", city: "Mumbai", country: "India", comments: "" },
  { name: "Plutus WM", address: "A-108, The Capital, Plot No. C-70, G-Block, BKC", city: "Mumbai", country: "India", comments: "Boutique proprietary investment firm focused on long-term wealth building." },
  { name: "Kredent Capital", address: "EP-J I/14, EP Block, Sector V, Bidhannagar", city: "Kolkata", country: "India", comments: "" },
  { name: "Dalton Investment (India)", address: "Dextrus, A-802, Crescenzo, G-Block", city: "Mumbai", country: "India", comments: "" },
  { name: "Tusk Investments", address: "22, Jassal House, 4-A Auckland Square", city: "Kolkata", country: "India", comments: "" },
  { name: "Burman Capital Management", address: "1st Floor, Express Building, Bahadur Shah Zafar Marg", city: "New Delhi", country: "India", comments: "" },
  { name: "Equity Intelligence India", address: "5th Floor, Areekal Mansion, Panampilly Nagar", city: "Kochi", country: "India", comments: "" },
  { name: "Creaegis Principals", address: "776, 100 Feet Road, HAL II Stage", city: "Bengaluru", country: "India", comments: "" },
  { name: "RatnaTraya Capital", address: "Indiqube 6th Floor, Leela Galleria, Old Airport Road", city: "Bengaluru", country: "India", comments: "" },
  { name: "Indgrowth Capital", address: "Tower A - 602, 6th Floor, Express Zone, Malad (East)", city: "Mumbai", country: "India", comments: "Alternative investment management focused on equity-centric strategies." },
  { name: "Middleton Capital", address: "Apeejay House, 130, Mumbai Samachar Marg, Fort", city: "Mumbai", country: "India", comments: "Chicago-based private investment firm pursuing opportunistic capital deployment." },
  { name: "Accelpru Investments", address: "95, Floor-9, Plot-223, Maker Chamber III, Nariman Point", city: "Mumbai", country: "India", comments: "Research-driven equity strategy with diversified portfolios." },
  { name: "Laburnum Capital Advisors", address: "D 64 Defence Colony, 3rd Floor", city: "New Delhi", country: "India", comments: "" },
  { name: "AlphaStreet", address: "Wall St", city: "San Francisco", country: "United States", comments: "" },
  { name: "Nvest", address: "Pease International Tradeport, Two International Drive, Suite 110", city: "Portsmouth", country: "United States", comments: "Registered investment adviser and wealth management platform." },
  { name: "AAA Investment", address: "14, Raman Avenue, Vandikaran Street, Velachery", city: "Chennai", country: "India", comments: "Personalized financial advisory for comprehensive wealth creation." },
  { name: "Ithought PMS", address: "", city: "Chennai", country: "India", comments: "" },
  { name: "ithought Financial Consulting", address: "554/555, Level 5, Capitale Towers, Anna Salai", city: "Chennai", country: "India", comments: "" },
  { name: "Prad Capital FO", address: "A-102, Ascot, Raheja Gardens", city: "Thane", country: "India", comments: "Family office managing proprietary capital with core strategy in Indian equity markets." },
  { name: "Counter Cyclical Investments", address: "401, PN 16, Shirkey Building, Raj Nagar", city: "Nagpur", country: "India", comments: "" },
  { name: "Chartered Capital & Investment", address: "711, Mahakant, Opp. V. S. Hospital, Ellisbridge", city: "Ahmedabad", country: "India", comments: "India-based merchant banking platform registered with SEBI since 1994." },
  { name: "Anubhuti Advisors", address: "602, Times Square Thaltej Shilaj Road", city: "Ahmedabad", country: "India", comments: "" },
];

export const INVESTOR_COUNTRIES = Array.from(new Set(INVESTORS.map(i => i.country).filter(Boolean))).sort();
export const INVESTOR_CITIES = Array.from(new Set(INVESTORS.map(i => i.city).filter(c => c && c !== "NA" && c !== "N/A"))).sort();
