// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnmioozueiudekegjbql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBubWlvb3p1ZWl1ZGVrZWdqYnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNjMwNDIsImV4cCI6MjA5MDYzOTA0Mn0.3FR8PhShezDUFn7rRYK0bX_dj3JcPqeZSNd7qzkRoDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});